# Generated by Django 2.2.7 on 2019-12-09 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='My Event')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('status', models.TextField(default='Started')),
                ('location', models.TextField(default='Manhattan')),
                ('radius', models.IntegerField(default=10)),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('restrictions', models.ManyToManyField(to='app.Restriction')),
            ],
        ),
        migrations.CreateModel(
            name='EventSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('event_id', models.BigIntegerField(db_index=True)),
                ('preferences', models.ManyToManyField(to='app.Restriction')),
            ],
        ),
    ]
