# Generated by Django 2.2.7 on 2019-12-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='link',
            new_name='slug',
        ),
    ]
