# Generated by Django 2.2.7 on 2019-12-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191205_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='diet_restrictions',
            field=models.ManyToManyField(to='app.Restriction'),
        ),
    ]
