# Generated by Django 2.2.7 on 2019-12-10 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_restriction_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsubmission',
            name='preferences',
            field=models.ManyToManyField(related_name='submission', to='app.Restriction'),
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.TextField(default='')),
                ('image_url', models.TextField(default='')),
                ('yelp_url', models.TextField(default='')),
                ('address', models.TextField(default='')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='app.Event')),
            ],
        ),
    ]
