# Generated by Django 2.2.7 on 2019-12-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191210_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='user_id',
            field=models.BigIntegerField(db_index=True, default=1),
            preserve_default=False,
        ),
    ]
