# Generated by Django 2.2.7 on 2019-12-06 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191206_0345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='owner',
        ),
        migrations.AddField(
            model_name='profile',
            name='restrictions',
            field=models.ManyToManyField(to='app.Restriction'),
        ),
    ]
