# Generated by Django 2.2.7 on 2019-12-06 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191206_0357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='restrictions',
        ),
    ]
